# Generated by Django 4.1.2 on 2022-10-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ident_one',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='ident_two',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='image_one',
            field=models.URLField(default='none', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='image_two',
            field=models.URLField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
